name: Twice Daily Contentful Fetch & Build

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and fetch data
        working-directory: ./json
        env:
          # Skrypt pobierze te wartości z bezpiecznego sejfu GitHuba
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: |
          npm install
          node fetch_data.js

      - name: Commit and push updated JSONs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin master
          
          # Dodajemy do zapisu tylko pliki JSON
          git add json/*.json
          
          # Sprawdza czy pliki faktycznie się zmieniły. Jeśli tak - zapisuje je w repo.
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: pobrano nowe dane z Contentful"
          git push origin HEAD:master